name = "Abyss"
os = "Windows"
type = "Standalone"
status = "Active"
staffQuality = "Poor"
access = "Paid"
website = "https://discord.gg/PsxTepWNYg"

[features]
movement = true
esp = true
crashers = true
