name = "Cat Client V3"
os = "Linux"
type = "BepInEx"
status = "Active"
staffQuality = "Good"
access = "Free"
website = "https://discord.gg/V3GpuQDGJu"

[features]
movement = true
esp = true
vr = true
