name = "Exo"
os = "Windows"
type = "Standalone"
status = "Active"
staffQuality = "Average"
access = "Free"
website = "https://exo-engine.com"

[features]
movement = true
esp = true
teleports = true
vr = true
crashers = false
protections = true
